<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.  Para Rodar comando: php artisan db:seed --class=CountriesTableSeeder
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Afeganistão', 'code' => 'AFG', 'capital' => 'Cabul'],
            ['name' => 'África do Sul', 'code' => 'ZAF', 'capital' => 'Pretória'],
            ['name' => 'Albânia', 'code' => 'ALB', 'capital' => 'Tirana'],
            ['name' => 'Alemanha', 'code' => 'DEU', 'capital' => 'Berlim'],
            ['name' => 'Andorra', 'code' => 'AND', 'capital' => 'Andorra-a-Velha'],
            ['name' => 'Angola', 'code' => 'AGO', 'capital' => 'Luanda'],
            ['name' => 'Antígua e Barbuda', 'code' => 'ATG', 'capital' => 'São João'],
            ['name' => 'Arábia Saudita', 'code' => 'SAU', 'capital' => 'Riad'],
            ['name' => 'Argélia', 'code' => 'DZA', 'capital' => 'Argel'],
            ['name' => 'Argentina', 'code' => 'ARG', 'capital' => 'Buenos Aires'],
            ['name' => 'Armênia', 'code' => 'ARM', 'capital' => 'Erevan'],
            ['name' => 'Austrália', 'code' => 'AUS', 'capital' => 'Camberra'],
            ['name' => 'Áustria', 'code' => 'AUT', 'capital' => 'Viena'],
            ['name' => 'Azerbaijão', 'code' => 'AZE', 'capital' => 'Baku'],
            ['name' => 'Bahamas', 'code' => 'BHS', 'capital' => 'Nassau'],
            ['name' => 'Bahrein', 'code' => 'BHR', 'capital' => 'Manama'],
            ['name' => 'Bangladesh', 'code' => 'BGD', 'capital' => 'Daca'],
            ['name' => 'Barbados', 'code' => 'BRB', 'capital' => 'Bridgetown'],
            ['name' => 'Bélgica', 'code' => 'BEL', 'capital' => 'Bruxelas'],
            ['name' => 'Beliz', 'code' => 'BLZ', 'capital' => 'Belmopan'],
            ['name' => 'Benin', 'code' => 'BEN', 'capital' => 'Porto-Novo'],
            ['name' => 'Bielorrússia', 'code' => 'BLR', 'capital' => 'Minsk'],
            ['name' => 'Bolívia', 'code' => 'BOL', 'capital' => 'Sucre'],
            ['name' => 'Bósnia e Herzegovina', 'code' => 'BIH', 'capital' => 'Sarajevo'],
            ['name' => 'Botsuana', 'code' => 'BWA', 'capital' => 'Gaborone'],
            ['name' => 'Brasil', 'code' => 'BRA', 'capital' => 'Brasília'],
            ['name' => 'Brunei', 'code' => 'BRN', 'capital' => 'Bandar Seri Begawan'],
            ['name' => 'Bulgária', 'code' => 'BGR', 'capital' => 'Sófia'],
            ['name' => 'Burkina Faso', 'code' => 'BFA', 'capital' => 'Ouagadougou'],
            ['name' => 'Burundi', 'code' => 'BDI', 'capital' => 'Gitega'],
            ['name' => 'Cabo Verde', 'code' => 'CPV', 'capital' => 'Praia'],
            ['name' => 'Camarões', 'code' => 'CMR', 'capital' => 'Yaoundé'],
            ['name' => 'Camboja', 'code' => 'KHM', 'capital' => 'Fnome Penh'],
            ['name' => 'Canadá', 'code' => 'CAN', 'capital' => 'Ottawa'],
            ['name' => 'Catar', 'code' => 'QAT', 'capital' => 'Doha'],
            ['name' => 'Cazaquistão', 'code' => 'KAZ', 'capital' => 'Nursultan'],
            ['name' => 'Chile', 'code' => 'CHL', 'capital' => 'Santiago'],
            ['name' => 'China', 'code' => 'CHN', 'capital' => 'Pequim'],
            ['name' => 'Chipre', 'code' => 'CYP', 'capital' => 'Nicósia'],
            ['name' => 'Colômbia', 'code' => 'COL', 'capital' => 'Bogotá'],
            ['name' => 'Comores', 'code' => 'COM', 'capital' => 'Moroni'],
            ['name' => 'Congo', 'code' => 'COG', 'capital' => 'Brazzaville'],
            ['name' => 'Congo, República Democrática do', 'code' => 'COD', 'capital' => 'Quinxassa'],
            ['name' => 'Coreia do Norte', 'code' => 'PRK', 'capital' => 'Pyongyang'],
            ['name' => 'Coreia do Sul', 'code' => 'KOR', 'capital' => 'Seul'],
            ['name' => 'Costa Rica', 'code' => 'CRI', 'capital' => 'San José'],
            ['name' => 'Costa do Marfim', 'code' => 'CIV', 'capital' => 'Yamoussoukro'],
            ['name' => 'Croácia', 'code' => 'HRV', 'capital' => 'Zagreb'],
            ['name' => 'Cuba', 'code' => 'CUB', 'capital' => 'Havana'],
            ['name' => 'Dinamarca', 'code' => 'DNK', 'capital' => 'Copenhague'],
            ['name' => 'Dominica', 'code' => 'DMA', 'capital' => 'Roseau'],
            ['name' => 'República Dominicana', 'code' => 'DOM', 'capital' => 'Santo Domingo'],
            ['name' => 'Egito', 'code' => 'EGY', 'capital' => 'Cairo'],
            ['name' => 'El Salvador', 'code' => 'SLV', 'capital' => 'San Salvador'],
            ['name' => 'Emirados Árabes Unidos', 'code' => 'ARE', 'capital' => 'Abu Dhabi'],
            ['name' => 'Equador', 'code' => 'ECU', 'capital' => 'Quito'],
            ['name' => 'Eritreia', 'code' => 'ERI', 'capital' => 'Asmara'],
            ['name' => 'Eslováquia', 'code' => 'SVK', 'capital' => 'Bratislava'],
            ['name' => 'Eslovênia', 'code' => 'SVN', 'capital' => 'Liubliana'],
            ['name' => 'Espanha', 'code' => 'ESP', 'capital' => 'Madri'],
            ['name' => 'Estados Unidos', 'code' => 'USA', 'capital' => 'Washington, D.C.'],
            ['name' => 'Estônia', 'code' => 'EST', 'capital' => 'Taline'],
            ['name' => 'Etiópia', 'code' => 'ETH', 'capital' => 'Adis Abeba'],
            ['name' => 'Fiji', 'code' => 'FJI', 'capital' => 'Suva'],
            ['name' => 'Filipinas', 'code' => 'PHL', 'capital' => 'Manila'],
            ['name' => 'Finlândia', 'code' => 'FIN', 'capital' => 'Helsinque'],
            ['name' => 'França', 'code' => 'FRA', 'capital' => 'Paris'],
            ['name' => 'Gabão', 'code' => 'GAB', 'capital' => 'Libreville'],
            ['name' => 'Gâmbia', 'code' => 'GMB', 'capital' => 'Banjul'],
            ['name' => 'Gana', 'code' => 'GHA', 'capital' => 'Acra'],
            ['name' => 'Grécia', 'code' => 'GRC', 'capital' => 'Atenas'],
            ['name' => 'Guatemala', 'code' => 'GTM', 'capital' => 'Cidade da Guatemala'],
            ['name' => 'Guiné', 'code' => 'GIN', 'capital' => 'Conakry'],
            ['name' => 'Guiné-Bissau', 'code' => 'GNB', 'capital' => 'Bissau'],
            ['name' => 'Guiné Equatorial', 'code' => 'GNQ', 'capital' => 'Malabo'],
            ['name' => 'Haiti', 'code' => 'HTI', 'capital' => 'Porto Príncipe'],
            ['name' => 'Holanda', 'code' => 'NLD', 'capital' => 'Amsterdã'],
            ['name' => 'Honduras', 'code' => 'HND', 'capital' => 'Tegucigalpa'],
            ['name' => 'Hungria', 'code' => 'HUN', 'capital' => 'Budapeste'],
            ['name' => 'Iémen', 'code' => 'YEM', 'capital' => 'Sana'],
            ['name' => 'Ilhas Marshall', 'code' => 'MHL', 'capital' => 'Majuro'],
            ['name' => 'Ilhas Salomão', 'code' => 'SLB', 'capital' => 'Honiara'],
            ['name' => 'Índia', 'code' => 'IND', 'capital' => 'Nova Délhi'],
            ['name' => 'Indonésia', 'code' => 'IDN', 'capital' => 'Jacarta'],
            ['name' => 'Irã', 'code' => 'IRN', 'capital' => 'Teerã'],
            ['name' => 'Iraque', 'code' => 'IRQ', 'capital' => 'Bagdá'],
            ['name' => 'Irlanda', 'code' => 'IRL', 'capital' => 'Dublin'],
            ['name' => 'Islândia', 'code' => 'ISL', 'capital' => 'Reiquiavique'],
            ['name' => 'Itália', 'code' => 'ITA', 'capital' => 'Roma'],
            ['name' => 'Jamaica', 'code' => 'JAM', 'capital' => 'Kingston'],
            ['name' => 'Japão', 'code' => 'JPN', 'capital' => 'Tóquio'],
            ['name' => 'Jordânia', 'code' => 'JOR', 'capital' => 'Amã'],
            ['name' => 'Kazakhstan', 'code' => 'KAZ', 'capital' => 'Nursultan'],
            ['name' => 'Quênia', 'code' => 'KEN', 'capital' => 'Nairóbi'],
            ['name' => 'Kiribati', 'code' => 'KIR', 'capital' => 'Tarawa'],
            ['name' => 'Kuwait', 'code' => 'KWT', 'capital' => 'Kuwait City'],
            ['name' => 'Laos', 'code' => 'LAO', 'capital' => 'Vientiane'],
            ['name' => 'Lesoto', 'code' => 'LSO', 'capital' => 'Maseru'],
            ['name' => 'Letônia', 'code' => 'LVA', 'capital' => 'Riga'],
            ['name' => 'Líbano', 'code' => 'LBN', 'capital' => 'Beirute'],
            ['name' => 'Libéria', 'code' => 'LBR', 'capital' => 'Monróvia'],
            ['name' => 'Líbia', 'code' => 'LBY', 'capital' => 'Trípoli'],
            ['name' => 'Liechtenstein', 'code' => 'LIE', 'capital' => 'Vaduz'],
            ['name' => 'Lituânia', 'code' => 'LTU', 'capital' => 'Vílnius'],
            ['name' => 'Luxemburgo', 'code' => 'LUX', 'capital' => 'Luxemburgo'],
            ['name' => 'Malásia', 'code' => 'MYS', 'capital' => 'Kuala Lumpur'],
            ['name' => 'Malawi', 'code' => 'MWI', 'capital' => 'Lilongwe'],
            ['name' => 'Maldivas', 'code' => 'MDV', 'capital' => 'Malé'],
            ['name' => 'Mali', 'code' => 'MLI', 'capital' => 'Bamaco'],
            ['name' => 'Malta', 'code' => 'MLT', 'capital' => 'Valeta'],
            ['name' => 'Marrocos', 'code' => 'MAR', 'capital' => 'Rabat'],
            ['name' => 'Maurício', 'code' => 'MUS', 'capital' => 'Port Louis'],
            ['name' => 'Mauritânia', 'code' => 'MRT', 'capital' => 'Nouakchott'],
            ['name' => 'México', 'code' => 'MEX', 'capital' => 'Cidade do México'],
            ['name' => 'Moldávia', 'code' => 'MDA', 'capital' => 'Quixinau'],
            ['name' => 'Mongólia', 'code' => 'MNG', 'capital' => 'Ulaanbaatar'],
            ['name' => 'Montenegro', 'code' => 'MNE', 'capital' => 'Podgorica'],
            ['name' => 'Namíbia', 'code' => 'NAM', 'capital' => 'Windhoek'],
            ['name' => 'Nauru', 'code' => 'NRU', 'capital' => 'Yaren'],
            ['name' => 'Nepal', 'code' => 'NPL', 'capital' => 'Catmandu'],
            ['name' => 'Nicarágua', 'code' => 'NIC', 'capital' => 'Manágua'],
            ['name' => 'Níger', 'code' => 'NER', 'capital' => 'Niamey'],
            ['name' => 'Nigéria', 'code' => 'NGA', 'capital' => 'Abuja'],
            ['name' => 'Noruega', 'code' => 'NOR', 'capital' => 'Oslo'],
            ['name' => 'Nova Zelândia', 'code' => 'NZL', 'capital' => 'Wellington'],
            ['name' => 'Omã', 'code' => 'OMN', 'capital' => 'Muscat'],
            ['name' => 'Países Baixos', 'code' => 'NLD', 'capital' => 'Amsterdã'],
            ['name' => 'Panamá', 'code' => 'PAN', 'capital' => 'Cidade do Panamá'],
            ['name' => 'Papua Nova Guiné', 'code' => 'PNG', 'capital' => 'Port Moresby'],
            ['name' => 'Paquistão', 'code' => 'PAK', 'capital' => 'Islamabad'],
            ['name' => 'Paraguai', 'code' => 'PRY', 'capital' => 'Assunção'],
            ['name' => 'Peru', 'code' => 'PER', 'capital' => 'Lima'],
            ['name' => 'Polônia', 'code' => 'POL', 'capital' => 'Varsóvia'],
            ['name' => 'Portugal', 'code' => 'PRT', 'capital' => 'Lisboa'],
            ['name' => 'Quênia', 'code' => 'KEN', 'capital' => 'Nairóbi'],
            ['name' => 'Quirguistão', 'code' => 'KGZ', 'capital' => 'Bishkek'],
            ['name' => 'Reino Unido', 'code' => 'GBR', 'capital' => 'Londres'],
            ['name' => 'República Centro-Africana', 'code' => 'CAF', 'capital' => 'Bangui'],
            ['name' => 'República Checa', 'code' => 'CZE', 'capital' => 'Praga'],
            ['name' => 'República do Congo', 'code' => 'COG', 'capital' => 'Brazzaville'],
            ['name' => 'República Dominicana', 'code' => 'DOM', 'capital' => 'Santo Domingo'],
            ['name' => 'Romênia', 'code' => 'ROU', 'capital' => 'Bucareste'],
            ['name' => 'Ruanda', 'code' => 'RWA', 'capital' => 'Kigali'],
            ['name' => 'Rússia', 'code' => 'RUS', 'capital' => 'Moscovo'],
            ['name' => 'São Cristóvão e Nevis', 'code' => 'KNA', 'capital' => 'Basseterre'],
            ['name' => 'São Marino', 'code' => 'SMR', 'capital' => 'São Marino'],
            ['name' => 'São Tomé e Príncipe', 'code' => 'STP', 'capital' => 'São Tomé'],
            ['name' => 'Senegal', 'code' => 'SEN', 'capital' => 'Dacar'],
            ['name' => 'Serra Leoa', 'code' => 'SLE', 'capital' => 'Freetown'],
            ['name' => 'Sérvia', 'code' => 'SRB', 'capital' => 'Belgrado'],
            ['name' => 'Singapura', 'code' => 'SGP', 'capital' => 'Cingapura'],
            ['name' => 'Síria', 'code' => 'SYR', 'capital' => 'Damasco'],
            ['name' => 'Somália', 'code' => 'SOM', 'capital' => 'Mogadíscio'],
            ['name' => 'Sri Lanka', 'code' => 'LKA', 'capital' => 'Sri Jayawardenepura Kotte'],
            ['name' => 'Suécia', 'code' => 'SWE', 'capital' => 'Estocolmo'],
            ['name' => 'Suíça', 'code' => 'CHE', 'capital' => 'Berna'],
            ['name' => 'Suriname', 'code' => 'SUR', 'capital' => 'Paramaribo'],
            ['name' => 'Tailândia', 'code' => 'THA', 'capital' => 'Banguecoque'],
            ['name' => 'Taiwan', 'code' => 'TWN', 'capital' => 'Taipei'],
            ['name' => 'Tajiquistão', 'code' => 'TJK', 'capital' => 'Dushanbe'],
            ['name' => 'Tanzânia', 'code' => 'TZA', 'capital' => 'Dodoma'],
            ['name' => 'Timor-Leste', 'code' => 'TLS', 'capital' => 'Dili'],
            ['name' => 'Togo', 'code' => 'TGO', 'capital' => 'Lomé'],
            ['name' => 'Tonga', 'code' => 'TON', 'capital' => 'Nukualofa'],
            ['name' => 'Trinidad e Tobago', 'code' => 'TTO', 'capital' => 'Porto Espanha'],
            ['name' => 'Tunísia', 'code' => 'TUN', 'capital' => 'Tunis'],
            ['name' => 'Turcomenistão', 'code' => 'TKM', 'capital' => 'Asgabate'],
            ['name' => 'Turquia', 'code' => 'TUR', 'capital' => 'Ancara'],
            ['name' => 'Tuvalu', 'code' => 'TUV', 'capital' => 'Funafuti'],
            ['name' => 'Ucrânia', 'code' => 'UKR', 'capital' => 'Quieve'],
            ['name' => 'Uganda', 'code' => 'UGA', 'capital' => 'Campala'],
            ['name' => 'Uruguai', 'code' => 'URY', 'capital' => 'Montevidéu'],
            ['name' => 'Uzbequistão', 'code' => 'UZB', 'capital' => 'Tashkent'],
            ['name' => 'Vanuatu', 'code' => 'VUT', 'capital' => 'Port Vila'],
            ['name' => 'Vaticano', 'code' => 'VAT', 'capital' => 'Cidade do Vaticano'],
            ['name' => 'Venezuela', 'code' => 'VEN', 'capital' => 'Caracas'],
            ['name' => 'Vietnã', 'code' => 'VNM', 'capital' => 'Hanói'],
            ['name' => 'Zâmbia', 'code' => 'ZMB', 'capital' => 'Lusaca'],
            ['name' => 'Zimbábue', 'code' => 'ZWE', 'capital' => 'Harare'],
        ];

        DB::table('countries')->insert($countries);
    }
}
